name: flutter_not_paid
description: Client did not pay? Add this widget into your app and the app will fade away completely on reaching deadline.
version: 1.0.1
homepage: https://github.com/BirjuVachhani/flutter_not_paid/community

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.17.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
