name: not_paid
description: Client did not pay? Add this widget into your app and the app will fade away completely on reaching deadline.
version: 0.1.0
homepage: https://github.com/BirjuVachhani/flutter_not_paid/community

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0

flutter:
